"""add user_id to screeenings

Revision ID: bbb44ce40b0f
Revises: 44a9cdbbd8cd
Create Date: 2026-01-21 13:48:55.252462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb44ce40b0f'
down_revision: Union[str, Sequence[str], None] = '44a9cdbbd8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
